spring:
  application:
    name: travel
  profiles:
    default: local
server:
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        max-age: 12h

app:
  security:
    cors:
      allowed-origins:
        - http://localhost:5173
        - http://localhost:5174
    csrf-cookie:
      secure: false
      same-site: Lax
