spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:boilerplate}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME:boilerplate}
    password: ${DB_PASSWORD:boilerplate}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

firebase:
  credentials-path: ${FIREBASE_CREDENTIALS_PATH:classpath:firebase-service-account.json}
